---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/actionmailer-markdown.rb

Style/OpenStructUse:
  Exclude:
    - test/**/*.rb
