---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/actionmailer-markdown.rb
